name: Publish Package
on:
  push:
    tags:
      - v*
jobs:
  publish-npm:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: pnpm
      - run: pnpm install --no-frozen-lockfile
      - run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
